/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  theme: {
    extend: {
        "colors": {
            "surface-bright": "#31394d",
            "secondary": "#adc6ff",
            "surface-container-lowest": "#060e20",
            "on-error-container": "#ffdad6",
            "secondary-fixed-dim": "#adc6ff",
            "error": "#ffb4ab",
            "surface-variant": "#2d3449",
            "on-tertiary-fixed-variant": "#5516be",
            "surface-container-high": "#222a3d",
            "surface-tint": "#4edea3",
            "on-tertiary": "#3c0091",
            "secondary-fixed": "#d8e2ff",
            "on-secondary-fixed-variant": "#004395",
            "on-primary-fixed-variant": "#005236",
            "on-secondary-fixed": "#001a42",
            "inverse-on-surface": "#283044",
            "surface-container-low": "#131b2e",
            "tertiary-fixed": "#e9ddff",
            "surface-dim": "#0b1326",
            "primary-fixed-dim": "#4edea3",
            "on-secondary": "#002e6a",
            "on-surface": "#dae2fd",
            "on-primary": "#003824",
            "inverse-primary": "#006c49",
            "primary-container": "#10b981",
            "outline-variant": "#3c4a42",
            "tertiary-container": "#b090ff",
            "background": "#0b1326",
            "outline": "#86948a",
            "on-primary-fixed": "#002113",
            "on-tertiary-container": "#4600a7",
            "on-secondary-container": "#e6ecff",
            "surface": "#0b1326",
            "primary": "#4edea3",
            "tertiary": "#d0bcff",
            "on-background": "#dae2fd",
            "on-surface-variant": "#bbcabf",
            "on-tertiary-fixed": "#23005c",
            "on-error": "#690005",
            "surface-container-highest": "#2d3449",
            "tertiary-fixed-dim": "#d0bcff",
            "secondary-container": "#0566d9",
            "error-container": "#93000a",
            "on-primary-container": "#00422b",
            "primary-fixed": "#6ffbbe",
            "inverse-surface": "#dae2fd",
            "surface-container": "#171f33"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "sm": "12px",
            "lg": "40px",
            "md": "24px",
            "xl": "64px",
            "base": "8px",
            "margin": "32px",
            "xs": "4px",
            "gutter": "24px"
        },
        "fontFamily": {
            "display-lg": ["Outfit", "sans-serif"],
            "body-lg": ["Inter", "sans-serif"],
            "label-sm": ["Inter", "sans-serif"],
            "label-md": ["Inter", "sans-serif"],
            "headline-lg": ["Outfit", "sans-serif"],
            "headline-md": ["Outfit", "sans-serif"],
            "body-md": ["Inter", "sans-serif"]
        },
        "fontSize": {
            "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
            "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
            "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
            "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
            "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
        }
    },
  },
  plugins: [],
}
